//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Drawing;
    using System.IO;
    using System.Linq;

    public partial class DOIBONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOIBONG()
        {
            this.CAUTHUs = new HashSet<CAUTHU>();
            this.CHUYENNHUONGs = new HashSet<CHUYENNHUONG>();
            this.DIEMs = new HashSet<DIEM>();
            this.HUANLUYENVIENs = new HashSet<HUANLUYENVIEN>();
            this.DOIHINHCHINHs = new HashSet<DOIHINHCHINH>();
            this.ITEMs = new HashSet<ITEM>();
            this.TEAMOFLEAGUEs = new HashSet<TEAMOFLEAGUE>();
            this.TAPLUYENs = new HashSet<TAPLUYEN>();
            this.THONGTINGIAIDAUs = new HashSet<THONGTINGIAIDAU>();
            this.THONGTINTRANDAUs = new HashSet<THONGTINTRANDAU>();
        }
        public Image _Picture { get; set; }
        public Image Picture
        {
            get
            {
                if (HINHANH != null)
                {
                    MemoryStream stream = new MemoryStream(HINHANH.ToArray());
                    if (stream != null && HINHANH.Count() > 0)
                    {
                        Image image = Image.FromStream(stream);
                        return image;
                    }
                }


                return null;

            }
            set { _Picture = value; }

        }


        public string _QUOCGIA;
        public string QUOCGIA
        {
            get
            {
                var qg = DataProvider.ins.DB.QUOCTICHes.Find(IDQUOCTICH);

                return qg == null ? " " : qg.TENQUOCGIA;
            }
            set
            {
                if (value != null)
                {
                    _QUOCGIA = value;
                    QUOCTICH qt = DataProvider.ins.DB.Database.SqlQuery<QUOCTICH>("SELECT * FROM QUOCTICH WHERE TENQUOCGIA = @ID ", new SqlParameter("@ID", _QUOCGIA)).FirstOrDefault<QUOCTICH>();
                    if (qt != null)
                    {
                        IDQUOCTICH = qt.ID;

                    }
                }


            }

        }
        public string _TENTHANHPHO;
        public string TENTHANHPHO
        {
            get
            {
                var qg = DataProvider.ins.DB.DIADIEMs.Find(THANHPHO);

                return qg == null ? " " : qg.TENDIADIEM;

            }
            set
            {
                if (value != null)
                {
                    _TENTHANHPHO = value;
                    DIADIEM dd = DataProvider.ins.DB.Database.SqlQuery<DIADIEM>("SELECT * FROM DIADIEM WHERE TENDIADIEM = @ID ", new SqlParameter("@ID", _TENTHANHPHO)).FirstOrDefault<DIADIEM>();
                    if (dd != null)
                    {
                        THANHPHO = dd.ID;

                    }
                }
            }

        }
        public string HLV
        {
            get
            {
                if (ID != null)
                {
                    HUANLUYENVIEN hlv = DataProvider.ins.DB.Database.SqlQuery<HUANLUYENVIEN>("SELECT * FROM HUANLUYENVIEN WHERE IDDOIBONG = @ID AND CHUCVU LIKE 'HLV%'", new SqlParameter("@ID", ID)).FirstOrDefault<HUANLUYENVIEN>();
                    return hlv == null ? " " : hlv.HOTEN;

                }
                return "";

            }
            set { }

        }


        public byte[] HINHANHHLV
        {
            get
            {
                if (ID != null)
                {
                    HUANLUYENVIEN hlv = DataProvider.ins.DB.Database.SqlQuery<HUANLUYENVIEN>("SELECT * FROM HUANLUYENVIEN WHERE IDDOIBONG = @ID AND CHUCVU LIKE 'HLV%'", new SqlParameter("@ID", ID)).FirstOrDefault<HUANLUYENVIEN>();
                    return hlv.HINHANH;

                }
                return null;

            }
            set { }

        }
        public string ID { get; set; }
        public Nullable<int> IDQUOCTICH { get; set; }
        public Nullable<int> THANHPHO { get; set; }
        public byte[] HINHANH { get; set; }
        public string TEN { get; set; }
        public Nullable<int> SOLUONGTHANHVIEN { get; set; }
        public Nullable<System.DateTime> NGAYTHANHLAP { get; set; }
        public string SANNHA { get; set; }
        public string SODOCHIENTHUAT { get; set; }
        public Nullable<long> GIATRI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAUTHU> CAUTHUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENNHUONG> CHUYENNHUONGs { get; set; }
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HUANLUYENVIEN> HUANLUYENVIENs { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOIHINHCHINH> DOIHINHCHINHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEAMOFLEAGUE> TEAMOFLEAGUEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAPLUYEN> TAPLUYENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINGIAIDAU> THONGTINGIAIDAUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINTRANDAU> THONGTINTRANDAUs { get; set; }
    }
}
