//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOIHINHCHINH
    {
        public string IDDOIBONG { get; set; }
        public int IDCAUTHU { get; set; }
        public string VITRI { get; set; }
        public string VAITRO { get; set; }
    
        public virtual CAUTHU CAUTHU { get; set; }
        public virtual DOIBONG DOIBONG { get; set; }
    }
}
