//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELDSERVICE
    {
        public int idField { get; set; }
        public int idService { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual FIELD FIELD { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
