//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIELD()
        {
            this.FOOTBALLMATCHes = new HashSet<FOOTBALLMATCH>();
            this.FIELDSERVICEs = new HashSet<FIELDSERVICE>();
        }
    
        public int idField { get; set; }
        public Nullable<int> idDiaDiem { get; set; }
        public byte[] images { get; set; }
        public string fieldName { get; set; }
        public string technicalInformation { get; set; }
        public Nullable<int> numOfSeats { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual DIADIEM DIADIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOTBALLMATCH> FOOTBALLMATCHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIELDSERVICE> FIELDSERVICEs { get; set; }
    }
}
