//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ID { get; set; }
        public Nullable<int> IDTHONGTINTRANDAU { get; set; }
        public string IDDOIBONG { get; set; }
        public Nullable<int> IDITEMTYPE { get; set; }
        public string THOIGIAN { get; set; }
        public Nullable<int> IDCAUTHU { get; set; }
    
        public virtual CAUTHU CAUTHU { get; set; }
        public virtual DOIBONG DOIBONG { get; set; }
        public virtual THONGTINTRANDAU THONGTINTRANDAU { get; set; }
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
