//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFRESHTOKEN
    {
        public System.Guid id { get; set; }
        public int userId { get; set; }
        public string token { get; set; }
        public string jwtId { get; set; }
        public bool IsRevoked { get; set; }
        public System.DateTime IssuedAt { get; set; }
        public System.DateTime Expired { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
