//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROUND()
        {
            this.FOOTBALLMATCHes = new HashSet<FOOTBALLMATCH>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDGIAIDAU { get; set; }
        public string TENVONGDAU { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<int> SOLUONGDOI { get; set; }
        public string IDDISPLAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOTBALLMATCH> FOOTBALLMATCHes { get; set; }
        public virtual LEAGUE LEAGUE { get; set; }
    }
}
