//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIERSERVICE
    {
        public int idSupplier { get; set; }
        public int idService { get; set; }
        public Nullable<int> status { get; set; }

        [JsonProperty("idServiceNavigation")]
        public virtual SERVICE SERVICE { get; set; }
        [JsonProperty("idSupplierNavigation")]
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
