//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using DevExpress.Data.ODataLinq.Helpers;
    using DevExpress.DirectX.Common.Direct2D;
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Drawing;
    using System.IO;
    using System.Linq;

    public partial class TEAMOFLEAGUE
    {
        public int ID { get; set; }
        public Nullable<int> IDGIAIDAU { get; set; }
        public string IDDOIBONG { get; set; }
    
        public virtual DOIBONG DOIBONG { get; set; }
        public virtual LEAGUE LEAGUE { get; set; }

        public int soTranThang;
        public int SoTranThang
        {
            get
            {
                var list = DataProvider.ins.DB.Database.SqlQuery<THONGTINTRANDAU>("SELECT * FROM dbo.THONGTINTRANDAU, dbo.FOOTBALLMATCH, dbo.ROUND WHERE dbo.THONGTINTRANDAU.IDTRANDAU = dbo.FOOTBALLMATCH.ID AND dbo.FOOTBALLMATCH.IDVONG = dbo.ROUND.ID AND dbo.ROUND.IDGIAIDAU = @IDLEAGUE AND THONGTINTRANDAU.IDDOIBONG = @ID AND THONGTINTRANDAU.KETQUA = 1 ", new SqlParameter("@ID", IDDOIBONG), new SqlParameter("@IDLEAGUE",IDGIAIDAU)).ToList();
                 soBanThang =list.Count;
                return soBanThang;
            }
        }
        public int soBanThang;
        public int SoBanThang
        {
            get
            {
                int x = 0;
                var list = DataProvider.ins.DB.Database.SqlQuery<THONGTINTRANDAU>("SELECT * FROM dbo.THONGTINTRANDAU, dbo.FOOTBALLMATCH, dbo.ROUND WHERE dbo.THONGTINTRANDAU.IDTRANDAU = dbo.FOOTBALLMATCH.ID AND dbo.FOOTBALLMATCH.IDVONG = dbo.ROUND.ID AND dbo.ROUND.IDGIAIDAU = @IDLEAGUE AND THONGTINTRANDAU.IDDOIBONG = @ID AND THONGTINTRANDAU.KETQUA = 1 ", new SqlParameter("@ID", IDDOIBONG), new SqlParameter("@IDLEAGUE", IDGIAIDAU)).ToList();
                foreach (var item in list)
                {
                    if (item.DIEM != null) x +=(int)item.DIEM;
                }
                return x;
            }
        }
    }
}
