//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootBallProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINTRANDAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINTRANDAU()
        {
            this.ITEMs = new HashSet<ITEM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DIEM { get; set; }
        public Nullable<int> THEDO { get; set; }
        public Nullable<int> THEVANG { get; set; }
        public Nullable<int> KETQUA { get; set; }
        public string IDDOIBONG { get; set; }
        public Nullable<int> IDTRANDAU { get; set; }
        public string TENDOIBONG
        {
            get
            {
                var qg = DataProvider.ins.DB.DOIBONGs.Find(IDDOIBONG);

                return qg == null ? " " : qg.TEN;
            }
            set { }
        }
        public byte[] HINHANHDOIBONG
        {
            get
            {
                var qg = DataProvider.ins.DB.DOIBONGs.Find(IDDOIBONG);

                return qg == null ? null : qg.HINHANH;
            }
            set { }
        }
        public virtual DOIBONG DOIBONG { get; set; }
        public virtual FOOTBALLMATCH FOOTBALLMATCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
    }
}
